version: "3.0"

services:

  jenkins:

    container_name: jenkins

    user: 0:992

   

    image: jenkins/jenkins:alpine

    ports:

    - 50000:50000

    - 8080:8080

    volumes:

    - /home/ec2-user:/var/jenkins_home:rw

    - /home/ec2-user/local/bin/docker:/usr/bin/docker

    - /home/ec2-user/home/ec2-user/run/docker.sock:/var/run/docker.sock
