version: "3.3"
services:
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - 36000:8080
    environment:
      - "SWAGGER_JSON=/apis/index.yaml"
    volumes:
    - ./apis:/apis:ro
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /apis/index.yaml'
    volumes:
      - ./apis:/apis:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '37000:4010'
