version : "3.0"
services :
        jenkins:
                container_name: jenkins
                user: 1000:1000
                
                privileged: true
               
               
               
                image: jenkins/jenkins:alpine
                ports:
                        - 50000:50000
                        - 8080:8080

                volumes:
                        - ./jenkins-data:/var/jenkins_home:rw
                        - /usr/bin/docker:/usr/bin/docker
                        - /usr/bin/docker-compose:/usr/bin/docker-compose:rw
                        - /var/run/docker.sock:/var/run/docker.sock
                        

                        
                deploy:

                        resources:
                                limits:
                                        cpus: '0.5'
                                        memory: 1024m
                                        
